### ISSUE TITLE
Change resolution of site infographics

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev#104]
Could happen after main website is up, not a priority.

**Comment by Robinlovelace** [comment]
It would be good if the user could see where car and walking/cycling routes overlap. Hard to see scale, which is inconsistent, in width legends:

![image](https://user-images.githubusercontent.com/1825120/108996661-8f859380-7696-11eb-9b52-e03ff658ce1c.png)

**Comment by Siequnu** [comment]
Breaking out the legend into a separate PNG in almost all cases will be an advantage, as we can size that larger than the main map. 

This will be worth doing for the kind of map charts shown above that can't be easily generated with chart.js or a similar library.

**Comment by Robinlovelace** [comment]
> This will be worth doing for the kind of map charts shown above that can't be easily generated with chart.js or a similar library.

If you make graphics using JavaScript wouldn't you also want to create the legends in JavaScript @Siequnu ? That would seem most logical and consistent to me: either have the infographics and legends as pngs or as svg/similar rather than mixing these file formats. Happy to go with all png generated by code in this repo as a default and to see generating infographics in JS as a stretch.

**Comment by Siequnu** [comment]
That's right, what I'm referring to is the two different types of visual information we have — bar charts, stacked charts, etc which are easy to generate with a JS library, and then we have the spider graphs, map-based charts, and radars which are trickier and much further down the property list.

**Comment by Siequnu** [comment]
I don't envisage generating with JS the second, more complex type of graphic mentioned above any time soon, so it would be good for those kinds of graphics to have the changes mentioned (background, font-colour, labels) and a separately embeddable legend, so that it's legible even with the smaller thumbnail size charts we have.

**Comment by Robinlovelace** [comment]
> That's right, what I'm referring to is the two different types of visual information we have — bar charts, stacked charts, etc which are easy to generate with a JS library

OK but I still don't think the suggestion to split up legends from their graphics suggested here

> Breaking out the legend into a separate PNG in almost all cases will be an advantage

Is a good idea - I can think of several disadvantages of doing that. Let's go with default being the PNGs listed in https://github.com/cyipt/actdev-ui/issues/23 for now as a placeholder and then they can be incrementally replaced by better JS, html (which can be produced from R easily) and of course PNG versions according to priority/time tradeoffs over the next couple of weeks.

**Comment by Siequnu** [comment]
That's a good point — and your suggestion is definitely more scalable. Let's go with that - expecting we can start that late next week/early the following.

**Comment by mvl22** [comment]
The legend isn't legible as it is.

It'll be moved to JS as agreed above, but in the short term the current size must be increased as it literally can't be read.

**Comment by Siequnu** [comment]
This is now jsified, seems we have moved on from this stage!

**Comment by Robinlovelace** [comment]
I was leaving this open because I couldn't see a way to show the data in the opening issue in the app. @mvl22 or @Siequnu can you  show how this is in there? Can open a separate issue if needs be.
