### ISSUE TITLE
Most sites missing buildings_od geojson

### ISSUE THREAD

**Issue by Siequnu** [cyipt/actdev#105]
The majority of sites are missing the buildings_od geojson. This is a really cool sub-layer and would be great if these could be added.

**Comment by Robinlovelace** [comment]
Yes, and something mentioned by @MeganStreb is that a simple 'Trip attractors' layer showing schools, shops etc could be good. Not an MVP so will mark as a stretch issue but doable. This was just a byproduct of #28, good co-benefit of going down to the building level. I'm up for taking a look at some point so assigning to me.

**Comment by Siequnu** [comment]
Could buildings be done as a MVP, rather than stretch? Otherwise I'll remove that layer, as it's currently foreseen in the design.

**Comment by Robinlovelace** [comment]
> Could buildings be done as a MVP, rather than stretch? Otherwise I'll remove that layer, as it's currently foreseen in the design.

It depends what you mean by buildings. Do you mean buildings within the site boundary? If so yes. Otherwise I think pre-determined 'Destinations' such as shops, schools, (and maybe office buildings) etc is a higher priority as a layer. That would be better than the dump of all buildings. Note that to fix https://github.com/cyipt/actdev/issues/35 I greatly broadened the definition of a building.

**Comment by Siequnu** [comment]
I'm happy with any of those — for me the priority is understanding which data layers to expose in the UI. Currently the buildings layer can (only?) be seen on the Great Kneighton site. 

If a destinations geojson file is generated for each site I can quickly swap out the current buildings API call and visual toggle for that layer.

<img width="545" alt="Screenshot 2021-02-25 at 12 52 46" src="https://user-images.githubusercontent.com/11821606/109105203-63d2de00-7768-11eb-89f3-bceeadb0e21a.png">

**Comment by Robinlovelace** [comment]
Plan: 

- [x] create `site_buildings.geojson` as that looks good
- [x] create `trip_attractors.geojson` which is an important layer to show range of places people may need to visit beyond town and work.

**Comment by Robinlovelace** [comment]
Working on this. Heads-up @joeytalbot and @Siequnu as discussed today.

**Comment by Robinlovelace** [comment]
Update: I realised a the previous version of the script was treating any OSM polygon as a building! Fixed now.

![image](https://user-images.githubusercontent.com/1825120/109311612-ef6a6e80-783d-11eb-80f7-0c595019c046.png)

**Comment by Robinlovelace** [comment]
Running this for all sites now.

**Comment by Robinlovelace** [comment]
Heads-up @mvl22 (and @Siequnu if still awake!) can you check the data just pushed in the commit above and let me know asap if there are any issues with this file format. Looks good to me!

**Comment by Robinlovelace** [comment]
Cool thing: it also shows the neat procgen_houses created by @dabreegster. They look good in Allerton Bywater to me!

![image](https://user-images.githubusercontent.com/1825120/109314312-14141580-7841-11eb-9d6d-7068486792e1.png)

https://github.com/cyipt/actdev/blob/main/data-small/allerton-bywater/site_buildings.geojson

**Comment by Robinlovelace** [comment]
And also heads-up Dustin, Purpose is incoming! (Note that in reality the majority of these are Commute not shopping trips, another crease to iron out, probably mostly on my side, at some point.)

![image](https://user-images.githubusercontent.com/1825120/109314543-66edcd00-7841-11eb-967b-8efbb88721f1.png)

**Comment by mvl22** [comment]
Updated buildings URL so these will now come through.
