### ISSUE TITLE
Walk routes using only single origin produces bogus results

### ISSUE THREAD

**Issue by mvl22** [cyipt/actdev#108]
Looking at the Poundbury site, the use of having a single origin for walk routes produces a very artificial result.

The problem is that the northern half of the development would presumably walk over this Way, distorting the walk routing:
https://www.openstreetmap.org/way/566932132#map=17/50.71407/-2.45753&layers=N

This is not ideal for cycling either, but is probably acceptable for a prototype, because cycling is a form of transport that is sufficiently quick that there may only be a few minutes' difference between the edges of a development. But for walking this could easily be a 10-20 minute difference, meaning that directness of walking is far more important.

![Screenshot 2021-02-24 at 21 36 55](https://user-images.githubusercontent.com/361423/109069012-8a513480-76e8-11eb-822b-a9f427a1f08d.png)

**Comment by mvl22** [comment]
NB I've added a couple of Notes asking whether the north-east and south-east of the site are strictly footways or whether they are shared-use to permit cycling:

https://www.openstreetmap.org/note/2553985
https://www.openstreetmap.org/note/2553998

(This is just for background info - not relating to the walking point above directly.)

**Comment by Robinlovelace** [comment]
Heads-up @mvl22 this is fixed now: https://actdev.cyipt.bike/routenetwork:type=,buildings/#14.45/50.71494/-2.45884

However, this reveals a new issue: the walking routes are all uniform width, as documented here: https://github.com/cyipt/actdev-ui/issues/20

**Comment by mvl22** [comment]
> Heads-up @mvl22 this is fixed now.

Thanks, much better.

> However, this reveals a new issue: the walking routes are all uniform width, as documented here: cyipt/actdev-ui#20

Yes, known issue. Not a trivial fix sadly as there are different keys that need to be looked at for styling within the context of what is a single layer but accepting different datasets. It's doable though, just not a quick 1-minute fix.
