### ISSUE TITLE
Alpha UI

### ISSUE THREAD

**Issue by mvl22** [cyipt/actdev#11]
Initial work is to create an alpha UI which is a layer-based prototype currently with:

Data that we already have access to:

- [ ] Existing planning application data (e.g. number of large applications per LSOA zone based on data released by @aspeakman)
- [ ] PCT data, e.g. with summary statistics on quietness diversion factor at the LSOA level
- [ ] JTS data

Data that needs to be generated - to be done after https://github.com/cyipt/actdev/milestone/3 is done:

- [ ] Cyclability ratings

Extras (not MVP items from a planning perspective but nice to have):

- [ ] Traffic count summaries, e.g. growth in traffic
- [ ] Road network summaries (e.g. % network that is 20 mph or less from OSM)
- [ ] Road casualty summaries

shown and be prepared to add new GeoJSON sources as these emerge from the other tickets.

**Comment by Robinlovelace** [comment]
Here's an early prototype of a user interface for the JTS components: https://apps.saferactive.org/actdev-shiny-demo/

**Comment by Robinlovelace** [comment]
Closing as duplicated by #37

**Comment by mvl22** [comment]
![alpha1](https://user-images.githubusercontent.com/361423/106219706-df755580-61d1-11eb-9af0-356113153cf8.png)
