### ISSUE TITLE
Storytelling with A/B Street

### ISSUE THREAD

**Issue by dabreegster** [cyipt/actdev#114]
I'll use this issue to record observations about how individual sites look in A/B Street, with the aim of generating material to focus on in the workshop presentation. My general goal is to establish how abst adds value to the actdev story beyond the 2nd zoom level.

What I'd expect: abst's value is in the feedback loop of observing some problem in the simulation, editing the map to intervene, comparing quantitative results and watching the change, and repeating. The biggest challenge currently is that roads can't be widened, so if OSM doesn't have street parking or multiple lanes tagged in the sites, then the player has less opportunity to add cyclepaths.

**Comment by dabreegster** [comment]
# Poundbury

![Screenshot from 2021-02-28 12-00-42](https://user-images.githubusercontent.com/1664407/109431695-a7be2100-79bc-11eb-970a-573d7b72b334.png)
Bridport road and Damers are the bottleneck into/out of this site. These cars and the cyclist all want to go to Dorchester, but there are only two direct routes there. The roads have a single lane each direction, with barely any shoulder, from checking street imagery. In abst, there's no lane over-taking modeled yet, so the cars stack up behind the cyclist, making the bottleneck very apparent to the player. In reality, either many cyclists would take a much more circuitous route, they'd attempt to use the tiny sidewalk, or cars would be passing bikes in a manner that's unpleasant for both.

According to street imagery, Bridport has intermittent street parking starting around Williams. If we're focusing on this site particularly, it'd be worth tagging it.

One edit the player could attempt here is making Bridport and Damers one-way for cars, using the other lane for bikes. In reality, one car lane could become a two-way bike lane, but as mentioned at the top of this issue, that's not possible in abst yet. So here's a rendition of that, with Bridport just eastbound into Dorchester and Damers westbound into Poundbury:
![Screenshot from 2021-02-28 12-13-32](https://user-images.githubusercontent.com/1664407/109432101-77778200-79be-11eb-96a8-232a09164c57.png)
[oneways.json.txt](https://github.com/cyipt/actdev/files/6057880/oneways.json.txt)

This one-wayness ends at Albert Rd / Cornwall in Dorchester, although maybe it'd be better to extend it all the way to South St. Here's the baseline simulation with this change:
![Screenshot from 2021-02-28 12-16-30](https://user-images.githubusercontent.com/1664407/109432165-cd4c2a00-79be-11eb-9534-b656c92a3736.png)
Green is good (cyclists using dedicated lanes of some sort), red means cars & bikes sharing the same lane. But note red isn't necessarily bad; this view doesn't show if a bike and car were actually conflicting at that moment. Also note Damers is unused, because our scenarios still need return trips.

For comparison, here's the same view without any edits:
![Screenshot from 2021-02-28 12-19-55](https://user-images.githubusercontent.com/1664407/109432272-48154500-79bf-11eb-8f16-15b5a9043e0c.png)
Hovering over each road, about half the cycle traffic actually wants to use Damers, because it's a more direct route.

Some short-term TODOs to tell this story better:
- include return trips in the scenario
- measure cyclist/driver conflict events -- every time a car is immediately queued behind a bike. Count it per road segment. In reality, overtaking would likely occur here (and will be modeled that way in the future).
- Record the simulation results for baseline and go active, so easy comparisons can be made with any map edits. Have to first decide what sort of background traffic to include.


Next up, Leeds -- Robin showed me a specific idea around Headrow and Vicar.

**Comment by dabreegster** [comment]
Just recording notes for my planned demo in Poundbury. I'll record a few practice runs and send it offline.

Part 1: observe

- Add background traffic and slow down the speed.
- With the unzoomed view running, explain the data is from OSM and the 2011 census.
- Zoom into the crazy 5-way intersection, show agents interacting with the traffic signal.
- Follow an individual cyclist, showing the individual data.
- Show the "cycling activity" layer, pointing out roads with high contention.
- Zoom into an example of cars queueing behind a cyclist. Explain over-taking.

Part 2: intervene

- "Poundbury has some cycle infrastructure already, but let's see if we can improve it further and fix this point of contention."
- Edit individual lanes, reversing the direction and switching to a bike lane.
- Load the pre-made proposal, show the direction of the one-way and where the change ends.

Part 3: feedback loop

- Zoom in and verify the roads are working as intended.
- Open the relative throughput layer, show the north/south detour being used more.
- Back up to about 7am, open the traffic plot for one of the detours, and show the live timeseries comparison.
- How might this affect travel times overall? Don't treat simulation results as authoritative, but get an initial sense.
- Open the trip summary dashboard, show that the net effect is mostly neutral, maybe even a bit better.
- Use the trip table to drill down into individual differences. The trip that loses the most time has to detour because of the one-way, but they honestly could've just walked in the first place.

Part 4: conclusion

- This particular change with one-ways probably isn't a good idea, but hopefully A/B Street made it easy to quickly try it out.
- A/B Street has a few intended uses, but one relevant is to quickly prototype and visualize transportation changes around a site, and how they might affect movement.
- The other is public engagement -- use it to show your proposed designs and get feedback. Or even more radically, crowd-source: ask the public to edit the map and explore the design space themselves.

**Comment by dabreegster** [comment]
The presentation is ready, supported by this particular story in Poundbury. Closing this issue. In the future, we can explore more individual case studies.

**Comment by Robinlovelace** [comment]
Great work @dabreegster looking forward to it!
