### ISSUE TITLE
Rebuild all abstr scenarios

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev#132]
Heads-up @dabreegster I'm planning to rebuild all the abstr scenarios this morning, can you test for a sample sites, e.g. Great-Kneighton, Allerton Bywater and Poundbury before pulling in all this new data just to be sure?

**Comment by Robinlovelace** [comment]
Sanity check on data for one scenario file: file is of same size and structure so think this is fine:

```
diff --git a/data-small/bath-riverside/scenario_base.json b/data-small/bath-riverside/scenario_base.json
index 108ddc6..54e53bd 100644
--- a/data-small/bath-riverside/scenario_base.json
+++ b/data-small/bath-riverside/scenario_base.json
@@ -4,17 +4,17 @@
     {
       "origin": {
         "Position": {
-          "longitude": -2.3773,
-          "latitude": 51.3842
+          "longitude": -2.3771,
+          "latitude": 51.3851
         }
       },
       "trips": [
         {
-          "departure": 32095,
+          "departure": 29069,
           "destination": {
             "Position": {
-              "longitude": -2.3601,
-              "latitude": 51.3984
+              "longitude": -2.3444,
+              "latitude": 51.4
             }
           },
           "mode": "Drive",
@@ -25,20 +25,20 @@
     {
       "origin": {
         "Position": {
-          "longitude": -2.3791,
-          "latitude": 51.3872
+          "longitude": -2.3756,
+          "latitude": 51.3823
         }
       },
       "trips": [
         {

```

**Comment by Robinlovelace** [comment]
Error message for tyersal-lane:

```
Building for tyersal-lane
Reading layer `multipolygons' from data source `/mnt/57982e2a-2874-4246-a6fe-115c199bc6bd/data/osm/geofabrik_west-yorkshire-latest.gpkg' using driver `GPKG'
Simple feature collection with 460615 features and 25 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -2.189691 ymin: 53.4693 xmax: -1.147365 ymax: 53.97511
geographic CRS: WGS 84
Error in `[<-.data.frame`(`*tmp*`, ids_odd, c("x", "y"), value = logical(0)) : 
  replacement has 0 items, need 4
```

**Comment by dabreegster** [comment]
I'll spot check for a few sites, then reimport everything. Thanks for fixing all the issues upstream!

**Comment by Robinlovelace** [comment]
Great. Pay particular attention to LCID and Micklefield, I have reason to suspect that the results will not be quite right linked to an issue fixed before this latest round of data was generated: https://github.com/cyipt/actdev/commit/caed3cd2f7da5e4e8763060005f0aae76c8e81bb

**Comment by dabreegster** [comment]
Done! I'll deploy a new release once some more abst UI and bg traffic fixes are done.

... Although I just realized I forgot to run the new tool to add return and lunch trips. I'll do that when I'm back from an appt.

> Pay particular attention to LCID and Micklefield

What sort of validations should I be looking for? Main observation at Micklefield is that there are only 17 people total.
