### ISSUE TITLE
Create manual.md file to go on the Manual page

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev#142]
Currently we have these links on the landing page:

About > Report > 

Creating this file will allow it to be updated to be:

About > Report > Manual >

Building on https://github.com/cyipt/actdev-ui/issues/55 but documenting here as that's where the file will live.

**Comment by Robinlovelace** [comment]
I'm working on this now.

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110680868-0d868600-81d1-11eb-9342-62461b222b60.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110682147-876b3f00-81d2-11eb-96e9-b86203ec250e.png)

**Comment by mvl22** [comment]
Appearing dynamically at
https://actdev.cyipt.bike/manual/

**Comment by Robinlovelace** [comment]
> Appearing dynamically at
> https://actdev.cyipt.bike/manual/

:tada:

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110683382-d9f92b00-81d3-11eb-9ec4-8ac745637762.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110683635-27759800-81d4-11eb-83c3-6e5b4ddf224d.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110693965-f4390600-81df-11eb-8d7a-c37ea0e23f1f.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110697687-9a870a80-81e4-11eb-9e20-9874a7e2a9c4.png)
