### ISSUE TITLE
Content for slides

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev#145]
See slides here: https://github.com/cyipt/actdev/blob/main/code/tests/slides.Rmd

Opening this issue to put content on / discuss them.

![Peek 2021-03-10 17-31](https://user-images.githubusercontent.com/1825120/110671502-79afbc80-81c6-11eb-9dc5-52046b1d04c8.gif)

**Comment by dabreegster** [comment]
Any qualms if the entirety of my 10 minutes is the demo with A/B Street? Check the actdevp repo for a dry-run video.

I can also fill out some slides if people will refer back to these later.

**Comment by Robinlovelace** [comment]
No qualms with that, will save the A/B Street demo to you which is a good thing as lots to cover.

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110672803-f0998500-81c7-11eb-9f9a-d2019028dca4.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110673378-9ea52f00-81c8-11eb-9822-58d44e1ecae2.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110677777-75d36880-81cd-11eb-8c59-eb406066bc4a.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110678068-ca76e380-81cd-11eb-8dec-f191dfe708b6.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110678305-0e69e880-81ce-11eb-98aa-7d91fd71e81c.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110680124-20e52180-81d0-11eb-8bcd-333e6e0403ed.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110680440-85a07c00-81d0-11eb-9658-7f303e72372f.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110777119-ad3b2700-8258-11eb-87f9-553449faa757.png)

**Comment by Robinlovelace** [comment]
![Peek 2021-03-11 11-04](https://user-images.githubusercontent.com/1825120/110777940-9d701280-8259-11eb-9c17-c56f5b709c83.gif)

**Comment by Robinlovelace** [comment]
Heads-up @joeytalbot, @mvl22 and @dabreegster I've uploaded my slides here: https://www.robinlovelace.net/presentations/actdev-slides.html#1

Any comments on these welcome.

**Comment by Robinlovelace** [comment]
@mvl22 is there an easy way to serve those from the ActDev site? Could be worth adding a link to the 'ActDev presentation slides' if so.

**Comment by Robinlovelace** [comment]
In terms of the overall plan, I plan to use those slides in 2 places, highlighted in bold:

- Intro from the chair 14:00 - 14:10
- **About the tool 14:10 - 14:15** - up to slide 6: https://www.robinlovelace.net/presentations/actdev-slides.html#11
14:15 - 14:30

- Lynda Addison, Lead on planning and transport integration, Transport Planning Society

- Julian Sanchez, Active Travel, Programme Manager, Essex County Council

- Megan Streb, Partnership Manager, Sustrans

---

## Panel session

14.30  - 15.00

- Graham Smith, Urban Design Group
- Robin Lovelace, Associate Professor of Transport Data Science, Institute for Transport Studies, University of Leeds
- Lucy Taussig, Consultant, Active Travel

---

## About the ActDev project

15:00 - 15:55

- **The ActDev Tool, Robin Lovelace and Joey Talbot (15 min)** Joey will demo the tool for 2/3 sites after my intro slides from https://www.robinlovelace.net/presentations/actdev-slides.html#15
- Planning and routing data in the ActDev project, Martin Lucas-Smith (10 min)
- Traffic simulation in and around new development sites (10 min)
- Q&A (20 min)

- Breakout rooms 16:00 - 16:45

1. Locating development sites: moderator Lynda Addison
2. Policy: moderator Roger Geffen
3. Good design of development sites: moderator Joey Talbot
4. Planning/routing data: moderator Martin Lucas Smith
5. Technology: moderator Dustin Carlino

**Comment by Robinlovelace** [comment]
Update on slides: thinking of adding everyone on the team to the list so it can be a more general 'Intro to ActDev project', not just for our part.

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110797354-e5e6fa80-8270-11eb-8b9d-26b2ac1c0403.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110797848-79203000-8271-11eb-80be-99b8d7abcec5.png)

**Comment by mvl22** [comment]
> is there an easy way to serve those from the ActDev site? Could be worth adding a link to the 'ActDev presentation slides' if so.

How about adding, as a second short paragraph under 'Introduction', a new sentence:

_Slides giving an overview of the project_, created for a workshop in March 2021, are available.

and add the link there.

**Comment by Robinlovelace** [comment]
> How about adding, as a second short paragraph under 'Introduction', a new sentence:
> 
> _Slides giving an overview of the project_, created for a workshop in March 2021, are available.

Added to the manual.

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/110936020-26557f80-8328-11eb-9b1f-39dd73640962.png)
