### ISSUE TITLE
Add cycle parking layer

### ISSUE THREAD

**Issue by dabreegster** [cyipt/actdev#148]
Some feedback from the workshop: as levels of cycling increase, often the amount of parking doesn't keep up. We talked about some of the difficulties for modeling this in A/B Street, but at the very least, a useful layer in actdev might be just to show https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_parking, and perhaps to correlate it with the projected number of trips to destinations nearby.

**Comment by mvl22** [comment]
Cycle parking layer now added.

![Screenshot 2021-03-12 at 17 09 39](https://user-images.githubusercontent.com/361423/110973886-c1188300-8355-11eb-8747-9b2a2a8a432d.png)

**Comment by Robinlovelace** [comment]
Job done :tada:
