### ISSUE TITLE
Add parameter for targetting scenario in A/B Street

### ISSUE THREAD

**Issue by mvl22** [cyipt/actdev#150]
Robin requests that A/B Street needs a parameter so that we can target the starting scenario from the web GUI.

@dabreegster

**Comment by dabreegster** [comment]
There'll be a new release uploaded by the time you see this. You can pass `--actdev_scenario=go_active` in the URL now. Any other value defaults to the baseline scenario; if you want to always pass the URL param, `--actdev_scenario=base` is consistent with the naming in abst, but any other value is fine too.

The URL in abst automatically updates to include the current viewport, making it easier to share the URL. @Robinlovelace, should we do the same for the scenario? There are many other things we could capture in the URL, like the current simulation time, layer open, agent being followed, etc. Any thoughts where we ought to draw the line?

**Comment by dabreegster** [comment]
Confirming the new release works: https://actdev.cyipt.bike/abstreet/?--actdev=kidbrooke-village&--cam=13.2/51.45672/0.01572&--actdev_scenario=go_active

**Comment by Robinlovelace** [comment]
Impressive! I guess the only remaining step is to pass that `actdev_scenario` param from the web app.
