### ISSUE TITLE
Set-up auto-deployment system for prototype UI

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev#16]
Demo of a an app that auto-updates: https://apps.saferactive.org/actdev-shiny-demo/

Every commit to https://github.com/cyipt/actdev-shiny leads to an update to the deployment.

Potentially good for rapid prototyping.

**Comment by mvl22** [comment]
Yes, same as CyIPT.

**Comment by Robinlovelace** [comment]
Yes, just need to set it up for the JS version of the app, this one I guess: https://github.com/cyipt/actdev-ui

Thinking: the very rudimentary but good-for-rapid-prototyping UI widgets in https://apps.saferactive.org/actdev-shiny-demo/ can help people (me + @joeytalbot ; ) who lack proper font-end development skill demo and test out ideas.

**Comment by mvl22** [comment]
Site will auto-update every 5 minutes.

**Comment by Robinlovelace** [comment]
> Site will auto-update every 5 minutes.

Where? Looking at https://www.cyipt.bike/actdev/

**Comment by mvl22** [comment]
The Alpha Map UI site URL is what you created in the DNS yesterday.

https://actdev.cyipt.bike/

**Comment by Robinlovelace** [comment]
:+1:
