### ISSUE TITLE
remove redundant columns in all-sites.geojson

### ISSUE THREAD

**Issue by natesheehan** [cyipt/actdev#161]
remove "walk_base_rating", "cycle_base_rating","drive_base_rating"

**Comment by natesheehan** [comment]
```r
all_sites = subset(all_sites, select = -c(walk_base_rating,cycle_base_rating,drive_base_rating))
file.remove("data-small/all-sites.geojson")
sf::write_sf(all_sites,"data-small/all-sites.geojson")
```

I have used this on the main branch

**Comment by Robinlovelace** [comment]
> select = -c(walk_base_rating,cycle_base_rating,drive_base_rating)

Nice syntax!

**Comment by Robinlovelace** [comment]
Job done I think, right @natesheehan . Pro tip:

```
git commit -am 'Close #161'
```

Would close this issue, give it a try!
