### ISSUE TITLE
Images in CCAG booth

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev#189]
Currently they look a bit sketchy. Any ideas on better graphics? Heads-up @mvl22, @joeytalbot and @natesheehan 

![image](https://user-images.githubusercontent.com/1825120/130084640-3b693283-4371-4f3e-ae5e-6fe44c6df60e.png)

**Comment by Robinlovelace** [comment]
Current image: https://github.com/cyipt/actdev/blob/main/figures/lcid-v-wide-image3.png

And icon: https://github.com/cyipt/actdev/blob/main/figures/logo.png

![image](https://user-images.githubusercontent.com/1825120/130084842-aa902c51-edfa-421c-877e-7b00977e040d.png)

![image](https://user-images.githubusercontent.com/1825120/130084925-2a95e53d-0d8a-45f1-916f-bc764855211b.png)

**Comment by Robinlovelace** [comment]
Note: the top image needs to be 4:1 width:height and icon 1:1 (it's not currently, my bad).

**Comment by natesheehan** [comment]
Darker backgrounds or a completely new image?
<img width="949" alt="snip" src="https://user-images.githubusercontent.com/22789869/130086258-24caa4ac-655b-4ac0-8a7b-39d4e4fa46e8.png">
<img width="952" alt="snip2" src="https://user-images.githubusercontent.com/22789869/130086506-dca078d7-f571-4a7c-8243-efdd926fd287.png">

**Comment by Robinlovelace** [comment]
Looking good!

**Comment by Robinlovelace** [comment]
Related question: will the video in the booth auto record and be available after? Guess so.

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/130100807-a64abea6-0bf3-4f2d-b9e9-b844093417ff.png)
