### ISSUE TITLE
Modelling world slides

### ISSUE THREAD

**Issue by natesheehan** [cyipt/actdev#190]

**Comment by natesheehan** [comment]
![image](https://user-images.githubusercontent.com/22789869/135088260-e697f43a-a1b3-4a86-ba23-ba95ad5f8b6e.png)

**Comment by natesheehan** [comment]
![image](https://user-images.githubusercontent.com/22789869/135095007-475b081c-6b09-435d-bde7-7a1f1079f8a8.png)

**Comment by natesheehan** [comment]
![image](https://user-images.githubusercontent.com/22789869/135111008-3a4a61fe-bcd9-423d-87ef-25fca35c2158.png)

**Comment by Robinlovelace** [comment]
Slides looking good from the images posted here!

**Comment by natesheehan** [comment]
![presentation](https://user-images.githubusercontent.com/22789869/135117293-042da30b-8378-4c60-8ff1-a78162e82af0.gif)
initial design

**Comment by mvl22** [comment]
Please fix Simon’s name. Nuttall
