### ISSUE TITLE
Create UI milestones

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev#20]

**Comment by Robinlovelace** [comment]
How about something like 

- Alpha UI (done)
- Working concept with prototype of final functionality
- Polishing

We can add those last 2 versions or similar to https://github.com/cyipt/actdev/milestones and close this issue.

**Comment by mvl22** [comment]
See comment on the existing issue about UI tracking, at:

https://github.com/cyipt/actdev/issues/37#issuecomment-770443794

These could be turned into milestones if that existing ticket is not enough to track things.

**Comment by Robinlovelace** [comment]
> These could be turned into milestones if that existing ticket is not enough to track things.

That doesn't sound like an action - I'm just following up on this because we agreed to do this and it was assigned. Important to follow up on things and do what we agreed to do, or change direction in an agile way and then communicate about it as seems to be the case here. Another issue closed 🎉
