### ISSUE TITLE
Define study region surrounding developments based on OD data

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev#26]
Building on #23

**Comment by Robinlovelace** [comment]
Map produced by the code in the above commit: 

![image](https://user-images.githubusercontent.com/1825120/104242843-a27e3480-5457-11eb-8d99-051f3c5a566a.png)

**Comment by Robinlovelace** [comment]
Using MSOA zones touching that area - looks too arbitrary: 

![image](https://user-images.githubusercontent.com/1825120/104243287-423bc280-5458-11eb-88bf-bcb1155aeef8.png)

**Comment by Robinlovelace** [comment]
2km buffer looking better to me, I suggest boosting this to 3, 4 or 5 km: 
![image](https://user-images.githubusercontent.com/1825120/104243491-8af37b80-5458-11eb-8276-e1b0bf16aafe.png)

**Comment by Robinlovelace** [comment]
With a 5 km buffer

![image](https://user-images.githubusercontent.com/1825120/104243726-ede51280-5458-11eb-9a88-5775fcb411af.png)

**Comment by Robinlovelace** [comment]
A more concise region based on including only MSOA OD pairs with 100 or more people and a buffer width of 2km: 
![image](https://user-images.githubusercontent.com/1825120/104244506-731cf700-545a-11eb-9857-765ca0dfe427.png)

**Comment by Robinlovelace** [comment]
Issue with this definition of the boundary flagged by @joeytalbot it misses the actual site! Plan is to to an `st_intersection()` between the OD data and a buffer (I suggest 2km) around the site boundary. But what you have is fine to demonstrate the potential. Also great to see cycleways in there: 


![image](https://user-images.githubusercontent.com/1825120/104305563-bca22c00-54c4-11eb-831c-c1649a96344f.png)

On a different note (could be split out as a separate issue), does that look like a reasonably representation of the cycleway parallel to the road on Hills Road @mvl22 ?

**Comment by mvl22** [comment]
> look like a reasonably representation of the cycleway parallel to the road on Hills Road

Representation in what sense - did you mean visually? Which section of Hills Road - it is a very long road with considerable variation of infrastructure types. Unfortunately the sideroad is covered up... but after looking along the 1km road a bit I think it is probably Union Road. There there is a on-road cycle lane heading south, and a bus lane (without separate cycle lane) heading north. So the visual representation is not correct. The visual representation would be correct much further south if it were representing the bit at, say, Luard Road:

https://www.cyclestreets.net/photomap/93871/#16/52.1858/0.1391
(follow this north for 1-2km to see absolutely masses of Hills Road photos).

**Comment by Robinlovelace** [comment]
Great, yes I meant visually. Good to know, seems the busway is being shown as a cycleway? This probably belongs in a separate issue and for another day but heads-up @dabreegster - are these kinds of tag->representation issues modifiable for the purposes of the project?

**Comment by dabreegster** [comment]
For Hills road at Union, the abst representation seems faithful to the tagging: https://www.openstreetmap.org/way/4276099
I don't see any bus lanes tagged here.

There are a number of import issues in Trumpington; I've filed https://github.com/dabreegster/abstreet/issues/449 to track these. Will try and have a look today.

**Comment by mvl22** [comment]
> For Hills road at Union, the abst representation seems faithful to the tagging: https://www.openstreetmap.org/way/4276099
> I don't see any bus lanes tagged here.

Urgh, typical that bus lanes aren't properly present in OSM, even in Cambridge.

Fixed with detailed tagging and ways split in:
https://www.openstreetmap.org/changeset/97382756
