### ISSUE TITLE
Traffic count summaries, e.g. growth in traffic

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev#39]
Should be a few lines of code for #37.

**Comment by mvl22** [comment]
Included; it was just cut and paste of the API definition as expected.

![Screenshot 2021-01-29 at 01 35 00](https://user-images.githubusercontent.com/361423/106219884-3ed36580-61d2-11eb-8177-ed4d4a287ea7.png)

**Comment by Robinlovelace** [comment]
Looking good!
