### ISSUE TITLE
Zoom level 3: UI changes

### ISSUE THREAD

**Issue by dabreegster** [cyipt/actdev#44]
- On any particular map, emphasize the development site
  - I'll start by just highlighting the area in yellow (I'm not good at colors)
  - Maybe this could be a toggleable layer, but I suspect we always want to point it out
- Possibly distinguish people (on the minimap, zoomed out, zoomed in, on the trip table, info panels, etc) as living in the development
  - Right now the scenario only has people in the development, so not needed
- Call out mode choice
  - Click a building, on the people tab show a quick summary "4 cyclists, 2 drivers" or something
  - Possibly make a new toggleable layer showing a heatmap of where drivers live (aka, pointing out areas without amenities and cycling facilities)
- Load the web client with a certain zoom + bbox
  - OSM style would be `19/47.53590/-122.27265`
  - Depending how zoom level 2 invokes 3, maybe something will also have to pick the right map filename
- Strip out controls not relevant for the zoom level 3 deployment
  - For example, no title screen, challenge modes, tutorial, Seattle maps
  - Need to design / discuss this
  - Figure out if we want the 15min walkshed tool deployed also, and how to jump between the simulation / walkshed mode

**Comment by mvl22** [comment]
> emphasize the development site

Presumably this would need to have a polygon supplied by the caller in the URL?


> OSM style would be 19/47.53590/-122.27265

Yes, that would be the best pattern.


> Figure out if we want the 15min walkshed tool deployed also, and how to jump between the simulation / walkshed mode

I am not in favour of isochrone displays in any system unless they are based on genuine walkability/cycleability (quietness) rather than distance.

Otherwise this just reinforces the dreadful but common greenwashing practice of developers implying that their development is cycle-friendly, by claiming that people can reach N (polygon) locations within X minutes by bike from their development, even when it is (say) surrounded by hostile roads that you can technically cycle along but few would be motivated to.

**Comment by mvl22** [comment]
Tagging @Siequnu so he knows what may be coming.

**Comment by dabreegster** [comment]
> Presumably this would need to have a polygon supplied by the caller in the URL?

Maybe not. It depends how many development sites are in a single map. I'm using the large study area as the map -- http://abstreet.s3-website.us-east-2.amazonaws.com/dev/game/?--dev&cambridge/maps/great_kneighton.bin and http://abstreet.s3-website.us-east-2.amazonaws.com/dev/game/?--dev&cheshire/maps/chapelford.bin. If each of these maps only has one site, I can bake it in. If more, then I'll think about the right way to plumb in the "current" site.

> I am not in favour of isochrone displays in any system unless they are based on genuine walkability/cycleability (quietness) rather than distance.

Totally fair. My plan is to get everything end-to-end working on abst as quickly as possible, then spend Feb and March polishing. One of these big improvements would be focusing on the cost functions used for routing and isochrones.

**Comment by dabreegster** [comment]
Actually, now's not a bad time to partly pin down how zoom level 2 will call into level 3.

Question 1: Will it be easy for layer 2 to know the area name (https://github.com/cyipt/actdev/tree/main/data-small) and pass that in? The URL for abst could either be something like:
- `.../abst?cambridge/maps/great_kneighton.bin&bbox=19/47.53590/-122.27265`
- or `.../abst?bbox=19/47.53590/-122.27265`
If it's the latter, I'll make something to find the correct map file from the bounding box.

Question 2: Are any of the study areas (https://github.com/cyipt/actdev/tree/main/geojsons) close to each other, so that we'd wind up sharing a map?
- If no, then each map can bake in the study area, and it won't have to be specified in the URL
- If so, then we might add a query parameter like `&site=great_kneighton`

**Comment by mvl22** [comment]
Just a note to flag that if (as is presumably likely) Amazon have any kind of user data logging enabled (e.g. IP addresses) for that AWS hosting, given that we are a UK-funded service subject to UK (based on EU) data protection rules, they will need to be hosted in a UK or EU Availability Zones, not US (e.g. us-east-2).

I think in this case we're not merely incidentally linking to a third-party service, because the project is part-funding (a small part of) its development and treating it as a part of our UI approach.

**Comment by mvl22** [comment]
> I'll make something to find the correct map file from the bounding box

That presumably won't scale sensibly when more and more areas get added. Cities have more than one major development, so they are going to start overlapping. If the tech are separate instances, I would work on the assumption that the instance needs to be referenced explicitly.

**Comment by dabreegster** [comment]
> they will need to be hosted in a UK or EU Availability Zones

Sounds good. Right now I have an S3 bucket just in `us-east-2` and am hosting the web app directly off of that. I don't think I've enabled any logging at all, but I dunno what they collect by default. For actdev, we can deploy everything to a separate S3 bucket or any HTTP fileserver. Besides making sure the server sends `Content-Type` headers, there's nothing special about hosting the web version.

> If the tech are separate instances, I would work on the assumption that the instance needs to be referenced explicitly.

Great, then I'll expect the names `chapelford` and `great_kneighton` and such as input. As the study areas start to partly overlap, I might have to re-evaluate how many different maps are created to cover these. abst doesn't chop the world into tiles and buffer in more data near boundaries; polygons around different areas of interest are explicitly drawn.

**Comment by dabreegster** [comment]
![Screenshot from 2021-01-27 13-01-23](https://user-images.githubusercontent.com/1664407/106053714-f6b42600-609f-11eb-9d85-363f81e5c450.png)
You can now pass `--study_area=great_kneighton` or similar on the command line, with the equivalent HTTP query param, and get the area highlighted.

**Comment by dabreegster** [comment]
![Screenshot from 2021-01-27 13-44-27](https://user-images.githubusercontent.com/1664407/106058218-cd969400-60a5-11eb-80d5-6163cc97c3aa.png)

Not sure the mode breakdown by people currently in the building (not the same as residents of that building) is so useful.

**Comment by dabreegster** [comment]
You can now pass `&cam=18/47.63234/-122.30656` and start centered somewhere, but I don't yet have the math for the zoom level working.

**Comment by dabreegster** [comment]
Closing in favor of #66
