### ISSUE TITLE
Create spider-map from each site to enable visualisation of decay of cycling levels

### ISSUE THREAD

**Issue by mvl22** [cyipt/actdev#47]
Create spider-map from each site, representing people starting cycling from the site and gradually no longer cycling as barriers are encountered.

Aims to tell the story of how people are able to get out out from the site.

See: https://github.com/cyipt/actdev/issues/45#issuecomment-769748529 and https://github.com/cyipt/actdev/issues/45#issuecomment-769754955

Needs a distance-decay model based on (a) cycleability and (b) distance.

The thickness of the lines would indicate the number of people cycling. **Busy roads would provide an immediate visualisation of 'eating away' at routes from O-D.**

At this stage, scope is showing the current state. _Future work_ that 'creates' potential new cycle infrastructure could then show the difference using the same model (i.e. before and after spider maps).

Needs R code written to implement the distance-decay model.

**Comment by mvl22** [comment]
> At this stage, scope is showing the current state. Future work that 'creates' potential new cycle infrastructure could then show the difference using the same model (i.e. before and after spider maps).

@Robinlovelace Can you confirm if this is correct (this was my understanding), or do you want to demote this? Would be useful so we know whether to expect this dataset to be forthcoming.

Personally I strongly think that showing the current state as a spider spread would provide a very strong story that a practitioner would instantly understand. Imagine a spider chart for a well-connected development vs one that is terrible - people would see at a glance the difference.

**Comment by Robinlovelace** [comment]
> @Robinlovelace Can you confirm if this is correct (this was my understanding), or do you want to demote this? Would be useful so we know whether to expect this dataset to be forthcoming.

One do discuss.

**Comment by Robinlovelace** [comment]
Closing for now as there is no action that can be implemented in code to solve the issue. The issue will be addressed by the route network data, as documented here: https://github.com/cyipt/actdev/issues/56

Happy to revisit and maybe re-open this issue if it gets to the point where there are actionable next steps to solve it but for now it's more about how we frame the outputs of the route network layer. Useful discussion, we can revive the idea of per-segment decay in Phase II.

**Comment by mvl22** [comment]
The rnet-fast lines are now in place (in https://github.com/cyipt/actdev-ui/commit/3b8ab800812694f3ce0738058e4b254b517962f5) and the numbers now do seem to add up when they branch.

I agree this looks like a phase 1 equivalent of the spider stuff, and it will appear that way when we fix a bug causing the line thicknesses not to show.
