### ISSUE TITLE
Build for new sites

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev#62]
Heads-up @joeytalbot, @mvl22 and @Siequnu I'm about to generate new data for the following sites for testing:

```
[1] "didcot"           "long-marston"     "taunton-firepool"
[4] "allerton-bywater" "handforth" 
```

Seem reasonable? I can add `great-kneighton` and `chapelford` to the list.

**Comment by Robinlovelace** [comment]
[data-sites-2021-02-08.zip](https://github.com/cyipt/actdev/files/5946362/data-sites-2021-02-08.zip)

Heads-up @mvl22 the data for the following sites is in there:

"taunton-firepool" "allerton-bywater"        "handforth" 
        "bailrigg"       "chapelford"  "great-kneighton"

**Comment by mvl22** [comment]
Just add the data to
https://github.com/cyipt/actdev/tree/main/data-small

in the same way as the other folders there.

Assuming the folder name matches the site_name in the all-sites.geojson file:
https://github.com/cyipt/actdev/blob/main/data-small/all-sites.geojson

it will then just work :)

Obviously allow the 5 minute cron to pull down the new files.

**Comment by Robinlovelace** [comment]
OK, although I was trying to minimise committing data. It's not huge though, so will give it a try!

**Comment by dabreegster** [comment]
Nice to see more of these! Should I import to A/B Street as well? (It'll force me to automate a little more of my importing process, maybe.) I can do the same Chapelford treatment and generate houses if OSM is missing lots of them. And later when the disaggregated OD script runs everywhere, I can bring in scenarios for all of these as well.

**Comment by Robinlovelace** [comment]
> Should I import to A/B Street as well?

Sure. I need to integrate the line disaggregation into the build script though...
