### ISSUE TITLE
Formally define dataset ranges

### ISSUE THREAD

**Issue by Siequnu** [cyipt/actdev#64]
Amongst others issues, #37, #45, #48, #54 and #55 make apparent a pending issue of scale. It could very well be that the success of our "story" inheres to the consistency of our data visualisation.

This is a UI/UX issue embodying consistency between data sets and visualisation between site- and national-level data. As data distribution will see-saw between regions, having some kind of global calibrative weight would increase the legibility and overall impact of the data — and the story — we present.

Would it be feasible to have some kind of overall idea of the scales involved for different data sources? 

It follows that these should be formally defined ranges, helping immensely in both the pre-launch data visualisation standardisation process and UI side of things, and also nipping in the bud any complexity in the post-launch data to be digested by our users.

There is evidently a flurry of activity to be expected in coming weeks, implying that a formal definition of these ranges will be a dynamic situation. 

But as soon as possible, inevitable scrum fluctuations notwithstanding, would these be possible to define, for the data sources in our dictionary?

A suggestion is that each dataset include an adjunct set of national-scope data variables, used for calibrating the site-level data.

**Comment by Siequnu** [comment]
@Robinlovelace, @joeytalbot, @mvl22 your thoughts?

**Comment by Robinlovelace** [comment]
Lets wait until the data dictionary issue and other questions in #54 are resolved first. But yes once that is sorted we can specify allowed ranges. Could that usefully go in the data dictionary csv files?

**Comment by Robinlovelace** [comment]
@mvl22 supported the idea of min-max values in the data dictionary. Suspect it will be more useful if these ranges are what the legends show rather than being hard limits on allowable values.

**Comment by Robinlovelace** [comment]
While this isn't complete I think it's out of scope for this project and requires a rethink for Phase II.
