### ISSUE TITLE
Import all sites into A/B Street

### ISSUE THREAD

**Issue by dabreegster** [cyipt/actdev#65]
In https://github.com/a-b-street/abstreet/commit/bbdd23dadab20fb479d591d30e89fbaa98037a3c, I just brought in 6 more sites, with a little bit of shell automation. Most painful thing was probably figuring out the Geofabrik region; on the plus side, I'm now slowly learning the geography of England. :)

I'm using this bug to track all of the work still needed, and more automation to make this even less tedious.

- [x] Update Chapelford manually; the small study area changed from when I originally imported it
- [x] Add lcid, which is a slightly special case, because it's just a district of a city that's already imported
- [x] Bring in the study area geojsons
- [x] Most sites need procgen houses
- [x] Make a new tool to recommend a Geofabrik source given a boundary polygon, using https://download.geofabrik.de/index-v1.json
- [x] Generate baseline and go dutch scenarios for all sites using `abstr`

**Comment by Robinlovelace** [comment]
Great, are you using the new `abstr` package to create the disag desire lines already? Impressive progress!

**Comment by dabreegster** [comment]
Ah not yet, updating the checklist. I need to play around with it and figure out how to point it to data from the actdev repo. Ultimately is that probably the better plan, to run the script and not check in the disaggregated json results into `data-small`? The files might grow based on population.

**Comment by Robinlovelace** [comment]
> Ultimately is that probably the better plan, to run the script and not check in the disaggregated json results into `data-small`?

I don't mind. I was holding back on committing large files to this repo but, given that it's not really a software project in the sense that we need to keep it super clean, I suggest we just push the jsons to `data-small` (which as you say soon may not be so small : ).

**Comment by Robinlovelace** [comment]
I'm up for incorporating the desire line disaggregation stage into the main `build.R` script which now loops through all sites. The fact that you've got the OSM data imported is awesome +++.

**Comment by dabreegster** [comment]
> I suggest we just push the jsons to data-small 

SGTM. My actdev shell script will just download the JSON files from raw.github and run them through the converter, then.

**Comment by Robinlovelace** [comment]
Heads-up @dabreegster I've just pushed a json file in the commit above. Let me know if that format is good to go. If it's a 👍 I'll push json files for other sites tomorrow. If not can revisit the new script. Note: in the absence of autogenerated buildings in some sites I've generated them using a simple random allocation which looks a bit dodgy but hopefully the resulting json data will still be just about OK:

![image](https://user-images.githubusercontent.com/1825120/107446961-69f57780-6b37-11eb-9357-18f229e72c3c.png)

**Comment by dabreegster** [comment]
Thanks! The import worked fine. We'll get unlucky if your generated buildings don't happen to be within 100m of mine. If you wanted to use the same buildings as A/B Street, you could grab http://abstreet.s3-website.us-east-2.amazonaws.com/dev/data/input/lancaster/procgen_houses.json.gz and such. The problem is that the **lancaster** parameter there is kind of made-up by me right now; I picked the nearest city-like thing for each site.

**Comment by dabreegster** [comment]
The other suggestion: output `baseline_scenario.json` and `godutch_scenario.json` and have different `scenario_name`s for each one

**Comment by dabreegster** [comment]
Everything's done for all sites in `data-small` now, and automation is in place to make it much easier to bring in more.

Only thing left is scenarios for each site, which'll use the work from https://github.com/a-b-street/abstr

**Comment by Robinlovelace** [comment]
True that @dabreegster - there was the upstream work on the desire lines data that I need to test so may not be until tomorrow that I produce the jsons. I have generated json files for all the folders currently in `data-small` but want to re-run the code after #70 was merged earlier today.

**Comment by dabreegster** [comment]
No rush! I appreciate the output; I'd have quite a time getting it incorporated in `scenarios-streamlined`

**Comment by Robinlovelace** [comment]
> The other suggestion: output `baseline_scenario.json` and `godutch_scenario.json` and have different `scenario_name`s for each one

Yes for sure.

**Comment by dabreegster** [comment]
Pretty much done here, but had some issues in halsnead (wound up with no map borders?) and wynyard (some problem with pathfinding). I'll dig in later.

**Comment by Robinlovelace** [comment]
All looking good, I think we can close this - certainly more than the 2 sites originally envisioned! There is more data to to import but the data that's in there is plenty good enough so closing for now :tada:
