### ISSUE TITLE
Disable parts of A/B Street UI

### ISSUE THREAD

**Issue by dabreegster** [cyipt/actdev#66]
![Screenshot from 2021-02-09 19-50-47](https://user-images.githubusercontent.com/1664407/107462179-64386b80-6b10-11eb-9477-6c20fa7c508b.png)

A few questions about trimming things down and preventing people from wandering off into other parts of abst.

1) The circled button in the top lets you change maps. Right now it'll list all maps in A/B Street, not just actdev ones, and the non-actdev ones will 404, which is quite an awkward experience. Do we want the ability to change sites from within abst at all, or do we want to rely on the other zoom level to do it?
2) Do we want to start by running the baseline scenario, or with an empty map?
3) If we start with the baseline, should we fast-forward time to 6 or 7am when the first trips start?
4) The bottom-left corner has a "home" button that'll take you back to the title screen, which has loads of irrelevant stuff, like "challenge modes" specific to Seattle. I'm guessing this button should totally go away. Do we want to replace it with an info button describing the actdev/abst integration a bit?
5) Most users probably won't fiddle with settings, but there are a few neat things in there, like isometric buildings. Keep it?
![Screenshot from 2021-02-09 19-58-55](https://user-images.githubusercontent.com/1664407/107462590-4586a480-6b11-11eb-9e77-8c2700b01749.png)

Any other desired changes to the abst UI to fit in better? Now that the e2e integration is there, I can also ask Yuwen's opinion (the abst UX expert).

**Comment by mvl22** [comment]
> Do we want the ability to change sites from within abst at all

Personally I'd say no. Best to have a clear entry point into a particular site with the context.

> Do we want to start by running the baseline scenario, or with an empty map?
> If we start with the baseline, should we fast-forward time to 6 or 7am when the first trips start?

I’d say that the user should be dumped into a state where they don’t have to press anything at all and can see visually stuff happening. It needs to be extremely obvious what is going on to an unfamiliar user. Best to start the simulation automatically, with a sensible time, and the user can start to fiddle things from that point.

**Comment by Robinlovelace** [comment]
> I’d say that the user should be dumped into a state where they don’t have to press anything at all and can see visually stuff happening. 

Agree with that from @mvl22. Follow-up question for @dabreegster will the scenarios still be available when accessing A/B Street from http://abstreet.s3-website.us-east-2.amazonaws.com/dev/game/ ?

That way if people want more settings we can point them there.

**Comment by dabreegster** [comment]
Thanks for the feedback! Most of the changes now implemented.

One new question came up: what traffic scenarios should be accessible?
![Screenshot from 2021-02-10 09-54-26](https://user-images.githubusercontent.com/1664407/107550544-05153e00-6b86-11eb-844f-2b332b845a28.png)
I'm inclined to just say the baseline and go dutch. "trips btwn home and work" and "random" use abst's very primitive generic activity models, and the US census data one is irrelevant here. Do we want to let the user simulate lots of traffic, not just the trips to/from the sites? If those simulations gridlock (quite likely), how would they interpret that in context of the points actdev is trying to get across?

And do we want to give them the "empty" option, which lets you spawn agents at an intersection or draw your own trips?

> will the scenarios still be available when accessing A/B Street from http://abstreet.s3-website.us-east-2.amazonaws.com/dev/game/ 

Yes, the normal deployment has all cities available, with all scenarios. Basically when you pass in the `--actdev` flag, it just disables a bunch of stuff so the user doesn't get lost.

**Comment by mvl22** [comment]
I would suggest a flag

--scenarios=baseline,go_dutch

> Basically when you pass in the --actdev flag, it just disables a bunch of stuff so the user doesn't get lost.

Based on years of designing APIs and having to maintain them for >10 years, I'd be cautious of starting to put too much stuff under one 'magic' flag. This stuff very quickly becomes a massive pain to manage, unless you are extremely careful to treat it as a special proxy for properly-defined flags (like e.g. scenarios above).

One approach might be a proper config file (loadable as a local reference only, not remote URLs), which then becomes a versioned set of parameters ultimately under the control of the project and versioned within the UI repo.

**Comment by dabreegster** [comment]
I'll keep the config creep in mind. At the moment, `--actdev` essentially acts like a small config file, doing its work in just one place.

My questions are about the UX -- should we let people simulate no traffic, spawn their own trips, use built-in methods to populate the entire map?

Also, Yuwen had some good feedback about the stripped-down UI: since we want to call attention to certain features that the user might not know about, we could just try adding a row of buttons at the top to do common things that we wish to emphasize. For example, "follow random trip" and shortcuts to some of the layers (like bike throughput, which breaks down by protected/unprotected infrastructure). I'll add a few of those tomorrow.

**Comment by Robinlovelace** [comment]
> should we let people simulate no traffic, spawn their own trips, use built-in methods to populate the entire map?

I see no reason why not. It's a prototype not a polished product we're aiming to produce. In fact, that would be ideal as a question to ask participants. We should create a survey to get user feedback after the workshop. New issue: https://github.com/cyipt/actdev/issues/72

Sounds like a good forward plan on the A/B Street side, feels like it's coming together really well with the zoom levels 2 and 3 integrated. Is a way of highlighting the site easy to do in A/B Street? Simple to add a polygon, e.g. a blue one with transparency as in the main actdev app I imagine.

**Comment by dabreegster** [comment]
> I see no reason why not

I guess since this is all open-ended, and it's generally relevant, then including SGTM. If we had a particular set of use cases that users were trying to satisfy, then cutting out distractions could be good.

> Is a way of highlighting the site easy to do in A/B Street?

This is done; https://github.com/cyipt/actdev/releases/tag/0.1.6 includes it, but it looks like that hasn't been deployed yet. Here's how it looks, with some zoomed/unzoomed/day/night variations. I am _not_ good at color; I could try the transparent blue.
![Screenshot from 2021-02-10 17-19-27](https://user-images.githubusercontent.com/1664407/107593405-25fc8400-6bc4-11eb-8a2e-068fbaeeaab0.png)
![Screenshot from 2021-02-10 17-19-09](https://user-images.githubusercontent.com/1664407/107593408-26951a80-6bc4-11eb-85e9-53d917b01ea1.png)
![Screenshot from 2021-02-10 17-18-18](https://user-images.githubusercontent.com/1664407/107593409-272db100-6bc4-11eb-9a1b-5628b1f50d6b.png)

**Comment by dabreegster** [comment]
![Screenshot from 2021-02-16 18-01-35](https://user-images.githubusercontent.com/1664407/108145898-0dd3ab80-7081-11eb-84b4-33ea6750eca9.png)
We now start with the baseline scenario running, and there are shortcuts to follow somebody moving around and to open up one of the most relevant layers. I'll think through what other shortcuts could be desirable.

Switching scenarios to dutch currently exits the dedicated actdev mode. I'm considering a bit more how much control to give people. Some different traffic patterns that might be relevant:
- none, to interactively spawn trips... likely a distraction
- the baseline / dutch scenarios, of course
- auto-generated "background" traffic for the rest of the map besides the development site. Likely going to adopt our simple "home to work" activity model for this.
- combining the baseline/dutch scenarios with the background traffic -- which would then require some UI changes to highlight agents that're part of the development, in... the unzoomed view, the zoomed view, info panels, trip tables

**Comment by Robinlovelace** [comment]
Split out from https://github.com/cyipt/actdev-ui/issues/14#issuecomment-780897389 (and agree this is a more appropriate place) 07:00 or even 08:00 may allow people to see interesting stuff happen quicker. In fact I vote 08:00 as we only have ~10s to capture attention (in real not A/B Street time ; ).

**Comment by Robinlovelace** [comment]
Great that it starts with the baseline scenario @dabreegster great stuff. I will track https://github.com/cyipt/actdev-ui/issues/16 and change the scenario names accordingly.

**Comment by mvl22** [comment]
For me the best change to make would be to avoid a long period at the start where nothing happens. I think it's not really obvious to a new user the purpose of the visualisation if nothing seems to happen almost as soon as they load it - it's a classic discoverabilty UI issue.

Also, from a usability perspective, I would make the yellow progress bar under the time draggable. I've tried to manipulate it so many times and then remembered that I found that won't work.

PS Can the top three boxes be made a consistent height, or at least the centre and right ones? Slightly different unaligned box heights are always a no-no in design terms. You could also ideally colour the user types in the top-right match their colour on the ground, to help people join these up cognitively. Sorry this is now a bit off-topic!

![Screenshot 2021-02-18 at 22 17 24](https://user-images.githubusercontent.com/361423/108428979-4cab6200-7237-11eb-998a-f700272f0e90.png)

**Comment by dabreegster** [comment]
Thanks for the UX feedback -- definitely not off-topic, it's always super helpful to get more eyes on this!

> For me the best change to make would be to avoid a long period at the start where nothing happens

Good point! I may try just starting by following somebody random. Or maybe if that's too invasive, flashing the "Follow someone" button a few times after the initial load.

(I'd also like to cut down the initial load time; lots of progress happened early January, but all the low-hanging fruit there is gone)

> I would make the yellow progress bar under the time draggable

I've had that UX conversation with @michaelkirk and Yuwen before. :) The main difficulty is that simulating forwards can be slow, depending on the size of the simulation, and rewinding actually involves reseting to midnight and then going forward -- even slower. Maybe we could do an experiment for the actdev integration and try this anyway -- since all of the scenarios are tiny, it should actually be pretty quick.

> Can the top three boxes be made a consistent height, or at least the centre and right ones?

Now that you point it out, I see why this is visually annoying. I'll see if there's a straightforward fix.

> You could also ideally colour the user types in the top-right match their colour on the ground

Ooh, we hadn't thought of that before! I'll pitch the idea to Yuwen.

**Comment by dabreegster** [comment]
> You could also ideally colour the user types in the top-right match their colour on the ground

I tried some variations of this:
![Screenshot from 2021-02-20 12-37-22](https://user-images.githubusercontent.com/1664407/108607994-aff0dd80-7378-11eb-86fe-4b495be51a4c.png)
![Screenshot from 2021-02-20 12-32-30](https://user-images.githubusercontent.com/1664407/108607995-b0897400-7378-11eb-96e4-c5ce89ff7290.png)
![Screenshot from 2021-02-20 12-32-15](https://user-images.githubusercontent.com/1664407/108607996-b0897400-7378-11eb-9703-47a8c3409b12.png)
![Screenshot from 2021-02-20 12-30-56](https://user-images.githubusercontent.com/1664407/108607997-b0897400-7378-11eb-9891-3d01f79740e0.png)
![Screenshot from 2021-02-20 12-30-17](https://user-images.githubusercontent.com/1664407/108607998-b1220a80-7378-11eb-9398-6a1535c2afa5.png)
But I'm not sure it looks good in both the day and night mode. Still thinking over this, but I like the idea of tying these counters more closely to the minimap controls and unzoomed map view.

**Comment by michaelkirk** [comment]
>  I like the idea of tying these counters more closely to the minimap controls and unzoomed map view.

Hmm, I'd never really thought about it before, but yeah, if there's a way to combine the "active trips" UI into the map controls, and get rid of that top/right panel all together... I'd love to see less control clutter.

**Comment by Robinlovelace** [comment]
From my perspective this is more than good enough. A bigger issue that has emerged is UI overlaps on some monitors. Closing this now because it's more than good enough for me and is partially replaced by this which is more important: https://github.com/a-b-street/abstreet/issues/551
