### ISSUE TITLE
Use procedurally generated houses for scenario generation

### ISSUE THREAD

**Issue by dabreegster** [cyipt/actdev#81]
https://github.com/cyipt/actdev/blob/a754ff9288c0e898451846ff364521e40d1fe53b/code/abstr-scenarios.R#L55
This code improves the disaggregation by using the same inferred houses that A/B Street generates. I'm now producing these houses for all sites that need them, with a URL that matches up with the site name. So we should be able to generalize this script now.

The URL is http://abstreet.s3-website.us-east-2.amazonaws.com/dev/data/input/**SITE**/procgen_houses.json.gz
**SITE** should be what you're using everywhere, including the directory names in `data-small`. There's one transformation: change all `-` to `_`. So for example, `newcastle-great-park` becomes `newcastle_great_park` for this URL.

Not all sites will have this file. When you get a 404, you can assume the site already has plenty of buildings upstream in OSM. I set the threshold at 1000 after observing some maps. For example, `dickens-heath` is already filled out, so I didn't generate more houses here.

**Comment by Robinlovelace** [comment]
Good thinking, this will improve the A/B Street scenarios substantially, the procedurally generated houses are way better. Giving it a shot now.

**Comment by Robinlovelace** [comment]
Good progress on this, I've implemented this and have generated the A/B Street scenario using procedurally generated houses as origins for Ashton Park. I plan to try to generate scenarios for the first 5 sites in alphabetical order and close this issue after pushing the results if it succeeds. Holding fire on regenerating all the .json files due to #82 which I suspect applies to other sites (there are fewer precedurally generated houses in the site area that `n_dwellings`).

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/107845182-844a8200-6dd1-11eb-81b5-d4012361db73.png)

Promising visualisation of resulting scenario for Ashton park though!

**Comment by Robinlovelace** [comment]
Results for Aylsbury (which is failing for some reason): 

![image](https://user-images.githubusercontent.com/1825120/107845274-3b46fd80-6dd2-11eb-8124-fe9e5e10a3db.png)

**Comment by Robinlovelace** [comment]
The latest commit fixed the issue for Aylsbury and I think uploaded new json data. The results look fine but highlight the issue of people walking long distances when the destination is a random point in a large zone that may be close or far from the origin, making me wonder about mode allocation probabilities at the individual level.

![image](https://user-images.githubusercontent.com/1825120/107845660-10aa7400-6dd5-11eb-8f64-972a805aac05.png)

**Comment by Robinlovelace** [comment]
Fixed for first 5 sites in alphabetical order.
