### ISSUE TITLE
Fewer 'procgen_houses' in site area than n_dwellings in sites data

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev#82]
Unfortunately they all seem to be outside the site boundary:

![image](https://user-images.githubusercontent.com/1825120/107844917-77c52a00-6dcf-11eb-92da-3468b8b3ee0c.png)

Heads-up @dabreegster my plan is to fix this edge case by expanding the site boundary now. 

It would be good if the procedural generation rules could ensure that there are `n_dwellings` new houses in the site boundary - doable?

**Comment by dabreegster** [comment]
The problem is that there are no roads (or really anything) in the site boundary. The houses only get generated along empty residential streets in OSM. Is this a case where we need to do #42 and draw roads based on site plans?

> It would be good if the procedural generation rules could ensure that there are n_dwellings new houses in the site boundary

See https://github.com/cyipt/actdev/issues/53#issuecomment-775342323 and next few comments. There's no relation between the generated houses and `n_dwellings` at all. I don't see an easy way to fix this -- we could count how many get generated in the site. If we made too many, randomly destroy some. If we made too few... maybe there's no room to make new houses, maybe there aren't any empty residential roads through the site.

**Comment by dabreegster** [comment]
https://www.openstreetmap.org/#map=15/51.3057/-2.1872
There's nothing around here. Satellite shows empty fields.

**Comment by Robinlovelace** [comment]
I guess the planned houses and roads haven't started being constructed yet. Looking at https://www.streetfocus.uk/map/#13/51.3057/-2.1872 I cannot see the planning application but imagine it's documented somewhere. 

I've tried searching for `tfnh "ashton park" development` online and have looked in the https://www.transportfornewhomes.org.uk/wp-content/uploads/2020/06/garden-village-visions.pdf which is where @joeytalbot got the list of sites from I think (there is another report, we should probably document this) but not sure which it is.

The example raises wider questions: 

Is it possible/worthwhile ensuring the number of buildings in the [site.geojson](https://github.com/cyipt/actdev/blob/main/data-small/ashton-park/site.geojson) is equal to the number of generated houses?  (Just checked and there are a whopping 2500 houses in that site, suggesting that we're going to see dozens of people spawning from each house in the current scenario*.json files unless we change something.)

Should we manually add or try to 'procgen' roads in sites like 'Ashton Park'?

What should we do when there is a difference between the number of dwellings in the site file and the number of procgen houses?

Lots of questions, we don't have to have definitive answers for, let alone solve, all of them in this round of work but worth thinking about.

Final related question: should I crack on and add updated .json files for all other 30 sites? I guess so but would like to make one more change first: https://github.com/cyipt/actdev/issues/83

**Comment by Robinlovelace** [comment]
And re these comments

> I don't see an easy way to fix this -- we could count how many get generated in the site. If we made too many, randomly destroy some. If we made too few... maybe there's no room to make new houses, maybe there aren't any empty residential roads through the site.

I guess comparing the number created vs number from the planning documents is worth doing. In cases where there is a big difference (e.g. factor of 5+) we could flag that there is issue. In fact we can do this already based on the jsons provided.  Perhaps a good next step is just to go ahead and create scenarios for all sites and generate a summary .csv reporting the difference so at least we know how big/small the issue is?

**Comment by Robinlovelace** [comment]
Update, I've just found this article about the specific site, mentions 2026 so no wonder they're not they're yet: https://www.gazetteandherald.co.uk/news/18225085.plan-takes-account-2-000-new-homes-planned-ashton-park/

**Comment by dabreegster** [comment]
> Is it possible/worthwhile ensuring the number of buildings in the site.geojson is equal to the number of generated houses?

I'm not convinced of this. A single building could represent a single-family home or a small apartment tower. `num_dwellings >= num_buildings`, right? Actually maybe my definition is off -- I've been reading "dwelling" as a "living unit", like one rentable apartment unit. There might be multiple people per unit, and multiple units per physical building.

> we're going to see dozens of people spawning from each house in the current scenario*.json files

If the houses are apartments, is that a problem? Even if they're meant to be homes, I guess it'll look unusual to someone watching closely, but if we're slightly wrong about how densely townhomes are packed together in a block, from the traffic simulation perspective, it's not so different for people to begin/end trips in adjacent buildings.

> Should we manually add or try to 'procgen' roads in sites like 'Ashton Park'?

Good question. Given how poor the support for maintaining a OSM diff is in ID and JOSM, in the short term, it's definitely a hassle. Longer-term, there could be a nice UI in abst and a well-thought-out format for representing the edits, so it could be easier to manually draw them. As for procedurally generating roads in a given area and connecting them to existing roads in a reasonable way, that's sounding much harder to me. There are plenty of people doing this in the procgen community, but I'm less confident I could hack something together quickly.

> Final related question: should I crack on and add updated .json files for all other 30 sites?

Yes, please. I vote to get data for all sites initially filled out, so we can get the demo working end-to-end. Then we can iterate on some of these problems. I'm assuming it's not a hassle to regenerate scenarios for all of the sites after some code changes.

**Comment by Robinlovelace** [comment]
I think we can probably close this, although the issue may have caused a few sites to fail. In any case I've logged the n. buildings in each site: https://github.com/cyipt/actdev/blob/main/data-small/sites_df_abstr.csv

Seems there's an issue with logging destinations, should be an easy fix. Main thing though, we're almost there on the scenarios!

**Comment by Robinlovelace** [comment]
Closing as out of scope for Phase I and to some extent superceded by #88
