### ISSUE TITLE
High-level output definition

### ISSUE THREAD

**Issue by mvl22** [cyipt/actdev#9]
This ticket aims to create a clear, high-level definition of what the final output will be in practice.

**Definition of the output of the project**

To create a tool which:

a) Provides a rating for the level of active travel provision (cycling and walking) between development sites and key services, to determine whether a location would be or is acceptable from health perspectives.

[data: JTS, PCT]
[users: council officers, developers looking for sites]
[link to github issue #1]

b) For known planned/existing development sites, the tool will provide additional analysis to inform specific improvements that could be made in active travel provision and proximity of key services within walking and cycling distance.

[data: segment-level route data from the PCT to work/school/ (and possibly) shops/doctors/other; PlanIt: needs large sites with dates]
[e.g.]
[campaigners, local authorities]
[link to github issue #2]
[Joey: Create dataset of large sites using TfNH reports of 20+ sites, for Andrew]
[Andrew: Validate existing very simplified rules against Joey's data on sites, in order to create an improved modelling of size; then expand geographical coverage]
[Simon: Routing from these sites to the locations outlined in #10]

c) makes the case for further work to create an interactive web application (including the underlying evolving evidence base) to do the above but on a national scale.

[national government, Roger Geffen]

**Stretch goals:**

(1) Expand (a) to include environmental and safety perspectives, not just health

(2) Use historical data to model the likely mode split associated with potential development sites.

**Comment by mvl22** [comment]
NB Previous project output:
https://cyipt.github.io/acton/articles/case-studies.html

**Comment by Robinlovelace** [comment]
This is done, thanks to great workshop with @mvl22, @joeytalbot and @Siequnu :tada:
