### ISSUE TITLE
Missing scenarios for some sites

### ISSUE THREAD

**Issue by dabreegster** [cyipt/actdev#96]
bath-riverside: godutch missing
ebbsfleet: both
handforth: both (there's a scenario.json)
tyersal-lane: both

The abst script expects `scenario-base.json` and `scenario-godutch.json`

**Comment by Robinlovelace** [comment]
Thanks @dabreegster there are a few edge cases to work round in these cases. Will take a look but may not be until early next week.

**Comment by dabreegster** [comment]
Thank you! All 34 sites now have scenarios.
